type_name = "Commodity"
description = '''

'''

[variants.GAS]
variant_name = "GAS"
description = '''
Identifier for Commodity GAS
'''

[variants.HEAT]
variant_name = "HEAT"
description = '''
Identifier for Commodity HEAT
'''

[variants.ELECTRICITY]
variant_name = "ELECTRICITY"
description = '''
Identifier for Commodity ELECTRICITY
'''

[variants.OIL]
variant_name = "OIL"
description = '''
Identifier for Commodity OIL
'''
