type_name = "ControlType"
description = """
Describes a resource's control type(s).

Control types describe how a resource is flexible. Typically, an RM will implement one control type, while a CEM will implement all five control types.
"""
see_also = [{ name = "Guide to S2 control types", link = "https://docs.s2standard.org/docs/concepts/control-types/" }]

[variants.POWER_ENVELOPE_BASED_CONTROL]
variant_name = "POWER_ENVELOPE_BASED_CONTROL"
description = """
Power Envelope Base Control, used for devices of which the power producing or consuming behavior cannot be controlled, but can be limited in some way.
"""

[variants.POWER_PROFILE_BASED_CONTROL]
variant_name = "POWER_PROFILE_BASED_CONTROL"
description = """
Power Profile Based Control, used for devices which have to perform a certain tasks, but that are flexible in when their tasks can be executed.
"""

[variants.OPERATION_MODE_BASED_CONTROL]
variant_name = "OPERATION_MODE_BASED_CONTROL"
description = """
Operation Mode Based Control, used for devices which can adjust their power producing or consuming behavior, without constraints regarding the duration of the adjustment.
"""

[variants.FILL_RATE_BASED_CONTROL]
variant_name = "FILL_RATE_BASED_CONTROL"
description = """
Fill Rate Based Control, used for devices which can store or buffer energy in some form.
"""

[variants.DEMAND_DRIVEN_BASED_CONTROL]
variant_name = "DEMAND_DRIVEN_BASED_CONTROL"
description = """
Demand Driven Based Control, used for devices which need to match a given demand of something, but are flexible in which way they satisfy this demand.
"""

[variants.NOT_CONTROLABLE]
variant_name = "NOT_CONTROLABLE"
description = """
`NOT_CONTROLABLE` is used when no control is possible. Resources of this type can still provide measurements and forecast.
"""

[variants.NO_SELECTION]
variant_name = "NO_SELECTION"
description = """
Identifier that is to be used if no control type is or has been selected. 
"""
