type_name = "Currency"
description = """
The currency used when this resource gives cost information.
"""
see_also = []

[variants.AED]
variant_name = "AED"
description = """
United Arab Emirates Dirham, the official currency of the United Arab Emirates.
"""

[variants.ANG]
variant_name = "ANG"
description = """
Netherlands Antillean Guilder, used in Curaçao and Sint Maarten.
"""

[variants.AUD]
variant_name = "AUD"
description = """
Australian Dollar, the official currency of Australia and its territories.
"""

[variants.CHE]
variant_name = "CHE"
description = """
WIR Euro, a complementary currency used in Switzerland.
"""

[variants.CHF]
variant_name = "CHF"
description = """
Swiss Franc, the official currency of Switzerland and Liechtenstein.
"""

[variants.CHW]
variant_name = "CHW"
description = """
WIR Franc, a complementary currency used in Switzerland.
"""

[variants.EUR]
variant_name = "EUR"
description = """
Euro, the official currency of the Eurozone, used by 20 European Union countries.
"""

[variants.GBP]
variant_name = "GBP"
description = """
Pound Sterling, the official currency of the United Kingdom.
"""

[variants.LBP]
variant_name = "LBP"
description = """
Lebanese Pound, the official currency of Lebanon.
"""

[variants.LKR]
variant_name = "LKR"
description = """
Sri Lankan Rupee, the official currency of Sri Lanka.
"""

[variants.LRD]
variant_name = "LRD"
description = """
Liberian Dollar, the official currency of Liberia.
"""

[variants.LSL]
variant_name = "LSL"
description = """
Lesotho Loti, the official currency of Lesotho.
"""

[variants.LYD]
variant_name = "LYD"
description = """
Libyan Dinar, the official currency of Libya.
"""

[variants.MAD]
variant_name = "MAD"
description = """
Moroccan Dirham, the official currency of Morocco.
"""

[variants.MDL]
variant_name = "MDL"
description = """
Moldovan Leu, the official currency of Moldova.
"""

[variants.MGA]
variant_name = "MGA"
description = """
Malagasy Ariary, the official currency of Madagascar.
"""

[variants.MKD]
variant_name = "MKD"
description = """
Macedonian Denar, the official currency of North Macedonia.
"""

[variants.MMK]
variant_name = "MMK"
description = """
Myanmar Kyat, the official currency of Myanmar.
"""

[variants.MNT]
variant_name = "MNT"
description = """
Mongolian Tögrög, the official currency of Mongolia.
"""

[variants.MOP]
variant_name = "MOP"
description = """
Macanese Pataca, the official currency of Macau.
"""

[variants.MRO]
variant_name = "MRO"
description = """
Mauritanian Ouguiya, the former currency of Mauritania (replaced by MRU).
"""

[variants.MUR]
variant_name = "MUR"
description = """
Mauritian Rupee, the official currency of Mauritius.
"""

[variants.MVR]
variant_name = "MVR"
description = """
Maldivian Rufiyaa, the official currency of the Maldives.
"""

[variants.MWK]
variant_name = "MWK"
description = """
Malawian Kwacha, the official currency of Malawi.
"""

[variants.MXN]
variant_name = "MXN"
description = """
Mexican Peso, the official currency of Mexico.
"""

[variants.MXV]
variant_name = "MXV"
description = """
Mexican Unidad de Inversion (UDI), a unit of account used in Mexico.
"""

[variants.MYR]
variant_name = "MYR"
description = """
Malaysian Ringgit, the official currency of Malaysia.
"""

[variants.MZN]
variant_name = "MZN"
description = """
Mozambican Metical, the official currency of Mozambique.
"""

[variants.NAD]
variant_name = "NAD"
description = """
Namibian Dollar, the official currency of Namibia.
"""

[variants.NGN]
variant_name = "NGN"
description = """
Nigerian Naira, the official currency of Nigeria.
"""

[variants.NIO]
variant_name = "NIO"
description = """
Nicaraguan Córdoba, the official currency of Nicaragua.
"""

[variants.NOK]
variant_name = "NOK"
description = """
Norwegian Krone, the official currency of Norway.
"""

[variants.NPR]
variant_name = "NPR"
description = """
Nepalese Rupee, the official currency of Nepal.
"""

[variants.NZD]
variant_name = "NZD"
description = """
New Zealand Dollar, the official currency of New Zealand and its territories.
"""

[variants.OMR]
variant_name = "OMR"
description = """
Omani Rial, the official currency of Oman.
"""

[variants.PAB]
variant_name = "PAB"
description = """
Panamanian Balboa, one of the official currencies of Panama (alongside USD).
"""

[variants.PEN]
variant_name = "PEN"
description = """
Peruvian Sol, the official currency of Peru.
"""

[variants.PGK]
variant_name = "PGK"
description = """
Papua New Guinean Kina, the official currency of Papua New Guinea.
"""

[variants.PHP]
variant_name = "PHP"
description = """
Philippine Peso, the official currency of the Philippines.
"""

[variants.PKR]
variant_name = "PKR"
description = """
Pakistani Rupee, the official currency of Pakistan.
"""

[variants.PLN]
variant_name = "PLN"
description = """
Polish Złoty, the official currency of Poland.
"""

[variants.PYG]
variant_name = "PYG"
description = """
Paraguayan Guaraní, the official currency of Paraguay.
"""

[variants.QAR]
variant_name = "QAR"
description = """
Qatari Riyal, the official currency of Qatar.
"""

[variants.RON]
variant_name = "RON"
description = """
Romanian Leu, the official currency of Romania.
"""

[variants.RSD]
variant_name = "RSD"
description = """
Serbian Dinar, the official currency of Serbia.
"""

[variants.RUB]
variant_name = "RUB"
description = """
Russian Ruble, the official currency of Russia.
"""

[variants.RWF]
variant_name = "RWF"
description = """
Rwandan Franc, the official currency of Rwanda.
"""

[variants.SAR]
variant_name = "SAR"
description = """
Saudi Riyal, the official currency of Saudi Arabia.
"""

[variants.SBD]
variant_name = "SBD"
description = """
Solomon Islands Dollar, the official currency of the Solomon Islands.
"""

[variants.SCR]
variant_name = "SCR"
description = """
Seychellois Rupee, the official currency of Seychelles.
"""

[variants.SDG]
variant_name = "SDG"
description = """
Sudanese Pound, the official currency of Sudan.
"""

[variants.SEK]
variant_name = "SEK"
description = """
Swedish Krona, the official currency of Sweden.
"""

[variants.SGD]
variant_name = "SGD"
description = """
Singapore Dollar, the official currency of Singapore.
"""

[variants.SHP]
variant_name = "SHP"
description = """
Saint Helena Pound, the official currency of Saint Helena.
"""

[variants.SLL]
variant_name = "SLL"
description = """
Sierra Leonean Leone, the official currency of Sierra Leone.
"""

[variants.SOS]
variant_name = "SOS"
description = """
Somali Shilling, the official currency of Somalia.
"""

[variants.SRD]
variant_name = "SRD"
description = """
Surinamese Dollar, the official currency of Suriname.
"""

[variants.SSP]
variant_name = "SSP"
description = """
South Sudanese Pound, the official currency of South Sudan.
"""

[variants.STD]
variant_name = "STD"
description = """
São Tomé and Príncipe Dobra, the former currency of São Tomé and Príncipe (replaced by STN).
"""

[variants.SYP]
variant_name = "SYP"
description = """
Syrian Pound, the official currency of Syria.
"""

[variants.SZL]
variant_name = "SZL"
description = """
Swazi Lilangeni, the official currency of Eswatini.
"""

[variants.THB]
variant_name = "THB"
description = """
Thai Baht, the official currency of Thailand.
"""

[variants.TJS]
variant_name = "TJS"
description = """
Tajikistani Somoni, the official currency of Tajikistan.
"""

[variants.TMT]
variant_name = "TMT"
description = """
Turkmenistani Manat, the official currency of Turkmenistan.
"""

[variants.TND]
variant_name = "TND"
description = """
Tunisian Dinar, the official currency of Tunisia.
"""

[variants.TOP]
variant_name = "TOP"
description = """
Tongan Paʻanga, the official currency of Tonga.
"""

[variants.TRY]
variant_name = "TRY"
description = """
Turkish Lira, the official currency of Turkey.
"""

[variants.TTD]
variant_name = "TTD"
description = """
Trinidad and Tobago Dollar, the official currency of Trinidad and Tobago.
"""

[variants.TWD]
variant_name = "TWD"
description = """
New Taiwan Dollar, the official currency of Taiwan.
"""

[variants.TZS]
variant_name = "TZS"
description = """
Tanzanian Shilling, the official currency of Tanzania.
"""

[variants.UAH]
variant_name = "UAH"
description = """
Ukrainian Hryvnia, the official currency of Ukraine.
"""

[variants.UGX]
variant_name = "UGX"
description = """
Ugandan Shilling, the official currency of Uganda.
"""

[variants.USD]
variant_name = "USD"
description = """
United States Dollar, the official currency of the United States and several other countries.
"""

[variants.USN]
variant_name = "USN"
description = """
United States Dollar (Next day), a financial instrument used in the US banking system.
"""

[variants.UYI]
variant_name = "UYI"
description = """
Uruguayan Peso en Unidades Indexadas, a unit of account used in Uruguay.
"""

[variants.UYU]
variant_name = "UYU"
description = """
Uruguayan Peso, the official currency of Uruguay.
"""

[variants.UZS]
variant_name = "UZS"
description = """
Uzbekistani Som, the official currency of Uzbekistan.
"""

[variants.VEF]
variant_name = "VEF"
description = """
Venezuelan Bolívar, the former currency of Venezuela (replaced by VES).
"""

[variants.VND]
variant_name = "VND"
description = """
Vietnamese Đồng, the official currency of Vietnam.
"""

[variants.VUV]
variant_name = "VUV"
description = """
Vanuatu Vatu, the official currency of Vanuatu.
"""

[variants.WST]
variant_name = "WST"
description = """
Samoan Tala, the official currency of Samoa.
"""

[variants.XAG]
variant_name = "XAG"
description = """
Silver (one troy ounce), a precious metal used as a financial instrument.
"""

[variants.XAU]
variant_name = "XAU"
description = """
Gold (one troy ounce), a precious metal used as a financial instrument.
"""

[variants.XBA]
variant_name = "XBA"
description = """
European Composite Unit (EURCO), a bond market unit.
"""

[variants.XBB]
variant_name = "XBB"
description = """
European Monetary Unit (E.M.U.-6), a bond market unit.
"""

[variants.XBC]
variant_name = "XBC"
description = """
European Unit of Account 9 (E.U.A.-9), a bond market unit.
"""

[variants.XBD]
variant_name = "XBD"
description = """
European Unit of Account 17 (E.U.A.-17), a bond market unit.
"""

[variants.XCD]
variant_name = "XCD"
description = """
East Caribbean Dollar, the official currency of eight Caribbean nations.
"""

[variants.XOF]
variant_name = "XOF"
description = """
West African CFA Franc, used by eight West African countries.
"""

[variants.XPD]
variant_name = "XPD"
description = """
Palladium (one troy ounce), a precious metal used as a financial instrument.
"""

[variants.XPF]
variant_name = "XPF"
description = """
CFP Franc, used in French Polynesia, New Caledonia, and Wallis and Futuna.
"""

[variants.XPT]
variant_name = "XPT"
description = """
Platinum (one troy ounce), a precious metal used as a financial instrument.
"""

[variants.XSU]
variant_name = "XSU"
description = """
SUCRE, a regional currency used by the ALBA trade bloc.
"""

[variants.XTS]
variant_name = "XTS"
description = """
Code reserved for testing purposes.
"""

[variants.XUA]
variant_name = "XUA"
description = """
ADB Unit of Account, used by the African Development Bank.
"""

[variants.XXX]
variant_name = "XXX"
description = """
No currency, used in cases where no currency is involved.
"""

[variants.YER]
variant_name = "YER"
description = """
Yemeni Rial, the official currency of Yemen.
"""

[variants.ZAR]
variant_name = "ZAR"
description = """
South African Rand, the official currency of South Africa.
"""

[variants.ZMW]
variant_name = "ZMW"
description = """
Zambian Kwacha, the official currency of Zambia.
"""

[variants.ZWL]
variant_name = "ZWL"
description = """
Zimbabwean Dollar, the former currency of Zimbabwe.
"""
