type_name = "DDBC.Instruction"
sent_by = []
description = '''
TODO
'''

[fields.abnormal_condition]
field_name = "abnormal_condition"
field_type = "boolean"
optional = false
description = '''
Indicates if this is an instruction during an abnormal condition
'''

[fields.actuator_id]
field_name = "actuator_id"
field_type = "ID"
optional = false
description = '''
ID of the actuator this Instruction belongs to.
'''

[fields.execution_time]
field_name = "execution_time"
field_type = "string"
optional = false
description = '''
Indicates the moment the execution of the instruction shall start. When the specified execution time is in the past, execution must start as soon as possible.
'''

[fields.id]
field_name = "id"
field_type = "ID"
optional = false
description = '''
Identifier of this `DDBC.Instruction`. Must be unique in the scope of the Resource Manager, for at least the duration of the session between Resource Manager and CEM.
'''

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = '''
ID of this message
'''

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = '''
TODO
'''

[fields.operation_mode_factor]
field_name = "operation_mode_factor"
field_type = "float"
optional = false
description = '''
The number indicates the factor with which the `OMBC.OperationMode` should be configured. The factor should be greater than or equal to 0 and less or equal to 1.
'''

[fields.operation_mode_id]
field_name = "operation_mode_id"
field_type = "ID"
optional = false
description = '''
ID of the `DDBC.OperationMode`
'''
