type_name = "DDBC.AverageDemandRateForecastElement"
description = '''

'''
see_also = []

[fields.demand_rate_expected]
field_name = "demand_rate_expected"
field_type = "float"
optional = false
description = """
The most likely value for the demand rate; the expected increase or decrease of the fill_level per second
"""

[fields.demand_rate_lower_68PPR]
field_name = "demand_rate_lower_68PPR"
field_type = "float"
optional = true
description = """
The lower limit of the range with a 68 % probability that the demand rate is within that range
"""

[fields.demand_rate_lower_95PPR]
field_name = "demand_rate_lower_95PPR"
field_type = "float"
optional = true
description = """
The lower limit of the range with a 95 % probability that the demand rate is within that range
"""

[fields.demand_rate_lower_limit]
field_name = "demand_rate_lower_limit"
field_type = "float"
optional = true
description = """
The lower limit of the range with a 100 % probability that the demand rate is within that range
"""

[fields.demand_rate_upper_68PPR]
field_name = "demand_rate_upper_68PPR"
field_type = "float"
optional = true
description = """
The upper limit of the range with a 68 % probability that the demand rate is within that range
"""

[fields.demand_rate_upper_95PPR]
field_name = "demand_rate_upper_95PPR"
field_type = "float"
optional = true
description = """
The upper limit of the range with a 95 % probability that the demand rate is within that range
"""

[fields.demand_rate_upper_limit]
field_name = "demand_rate_upper_limit"
field_type = "float"
optional = true
description = """
The upper limit of the range with a 100 % probability that the demand rate is within that range
"""

[fields.duration]
field_name = "duration"
field_type = "Duration"
optional = false
description = """
Duration of the element
"""
