type_name = "DDBC.ActuatorStatus"
sent_by = []
description = """

"""
see_also = []

[fields.active_operation_mode_id]
field_name = "active_operation_mode_id"
field_type = "ID"
optional = false
description = """
The operation mode that is presently active for this actuator.
"""

[fields.actuator_id]
field_name = "actuator_id"
field_type = "ID"
optional = false
description = """
ID of the actuator this messages refers to
"""

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = """
ID of this message
"""

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = """

"""

[fields.operation_mode_factor]
field_name = "operation_mode_factor"
field_type = "float"
optional = false
description = """
The number indicates the factor with which the `DDBC.OperationMode` is configured. The factor should be greater than or equal to 0 and less or equal to 1.
"""

[fields.previous_operation_mode_id]
field_name = "previous_operation_mode_id"
field_type = "ID"
optional = true
description = """
ID of the DDBC,OperationMode that was active before the present one. This value shall always be provided, unless the active `DDBC.OperationMode` is the first `DDBC.OperationMode` the Resource Manager is aware of.
"""

[fields.transition_timestamp]
field_name = "transition_timestamp"
field_type = "string"
optional = true
description = """
Time at which the transition from the previous `DDBC.OperationMode` to the active `DDBC.OperationMode` was initiated. This value shall always be provided, unless the active `DDBC.OperationMode` is the first `DDBC.OperationMode` the Resource Manager is aware of.
"""
