type_name = "EnergyManagementRole"
description = """
TODO
"""
see_also = []

[variants.CEM]
variant_name = "CEM"
description = """
Customer Energy Manager
"""

[variants.RM]
variant_name = "RM"
description = """
Resource Manager
"""
