type_name = "FRBC.OperationModeElement"
description = """
TODO
"""
see_also = []

[fields.fill_level_range]
field_name = "fill_level_range"
field_type = "NumberRange"
optional = false
description = """
The range of the fill level for which this `FRBC.OperationModeElement` applies. The start of the NumberRange shall be smaller than the end of the NumberRange.
"""

[fields.fill_rate]
field_name = "fill_rate"
field_type = "NumberRange"
optional = false
description = """
Indicates the change in fill_level per second. The lower_boundary of the NumberRange is associated with an operation_mode_factor of 0, the upper_boundary is associated with an operation_mode_factor of 1. 
"""

[fields.power_ranges]
field_name = "power_ranges"
field_type = "PowerRange[]"
optional = false
description = """
The power produced or consumed by this operation mode. The start of each PowerRange is associated with an operation_mode_factor of 0, the end is associated with an operation_mode_factor of 1. In the array there must be at least one PowerRange, and at most one PowerRange per CommodityQuantity.
"""

[fields.running_costs]
field_name = "running_costs"
field_type = "NumberRange"
optional = true
description = """
Additional costs per second (e.g. wear, services) associated with this operation mode in the currency defined by the ResourceManagerDetails, excluding the commodity cost. The range is expressing uncertainty and is not linked to the operation_mode_factor.
"""
