type_name = "FRBC.ActuatorDescription"
sent_by = []
description = """
TODO
"""
see_also = []

[fields.diagnostic_label]
field_name = "diagnostic_label"
field_type = "string"
optional = true
description = """
Human readable name/description for the actuator. This element is only intended for diagnostic purposes and not for HMI applications.
"""

[fields.id]
field_name = "id"
field_type = "ID"
optional = false
description = """
ID of the Actuator. Must be unique in the scope of the Resource Manager, for at least the duration of the session between Resource Manager and CEM.
"""

[fields.operation_modes]
field_name = "operation_modes"
field_type = "FRBC.OperationMode[]"
optional = false
description = """
Provided `FRBC.OperationModes` associated with this actuator
"""

[fields.supported_commodities]
field_name = "supported_commodities"
field_type = "Commodity[]"
optional = false
description = """
List of all supported Commodities.
"""

[fields.timers]
field_name = "timers"
field_type = "Timer[]"
optional = false
description = """
List of Timers associated with this actuator
"""

[fields.transitions]
field_name = "transitions"
field_type = "Transition[]"
optional = false
description = """
Possible transitions between `FRBC.OperationModes` associated with this actuator.
"""
