type_name = "FRBC.LeakageBehaviourElement"
description = """

"""
see_also = []

[fields.fill_level_range]
field_name = "fill_level_range"
field_type = "NumberRange"
optional = false
description = """
The fill level range for which this `FRBC.LeakageBehaviourElement` applies. The start of the range must be less than the end of the range.
"""

[fields.leakage_rate]
field_name = "leakage_rate"
field_type = "float"
optional = false
description = """
Indicates how fast the momentary fill level will decrease per second due to leakage within the given range of the fill level. A positive value indicates that the fill level decreases over time due to leakage.
"""
