type_name = "FRBC.TimerStatus"
sent_by = []
description = """
TODO
"""
see_also = []

[fields.actuator_id]
field_name = "actuator_id"
field_type = "ID"
optional = false
description = """
The ID of the actuator the timer belongs to
"""

[fields.finished_at]
field_name = "finished_at"
field_type = "string"
optional = false
description = """
Indicates when the Timer will be finished. If the DateTimeStamp is in the future, the timer is not yet finished. If the DateTimeStamp is in the past, the timer is finished. If the timer was never started, the value can be an arbitrary DateTimeStamp in the past.
"""

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = """
ID of this message
"""

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = """
TODO
"""

[fields.timer_id]
field_name = "timer_id"
field_type = "ID"
optional = false
description = """
The ID of the timer this message refers to
"""
