type_name = "FRBC.LeakageBehaviour"
sent_by = []
description = """
TODO
"""
see_also = []

[fields.elements]
field_name = "elements"
field_type = "FRBC.LeakageBehaviourElement[]"
optional = false
description = """
List of elements that model the leakage behaviour of the buffer. The fill_level_ranges of the elements must be contiguous.
"""

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = """
ID of this message
"""

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = """
TODO
"""

[fields.valid_from]
field_name = "valid_from"
field_type = "string"
optional = false
description = """
Moment this `FRBC.LeakageBehaviour` starts to be valid. If the `FRBC.LeakageBehaviour` is immediately valid, the DateTimeStamp should be now or in the past.
"""
