type_name = "Handshake"
sent_by = ["CEM", "RM"]
description = """
Message sent to initialize an S2 session.

When starting a new S2 session, `Handshake` should be the first message sent from both sides. The CEM should then send a `HandshakeResponse` to establish the S2 protocol version used in the session. The handshaking process should always occur at the start of a session, even if the specific CEM and RM already have many succesfull S2 sessions behind them.
"""
see_also = []

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = """
ID of this message.
"""

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = """
The string `"Handshake"`.
"""

[fields.role]
field_name = "role"
field_type = "EnergyManagementRole"
optional = false
description = """
The role of the sender of this message.
"""

[fields.supported_protocol_versions]
field_name = "supported_protocol_versions"
field_type = "string[]"
optional = true
description = """
Protocol versions supported by the sender of this message. This field is mandatory for the RM, but optional for the CEM.
"""
