type_name = "HandshakeResponse"
sent_by = ["CEM"]
description = """
Establishes the S2 protocol version to use during this S2 session.

The CEM sends this message after exchanging `Handshake`s with the RM.
"""
see_also = []

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = """
ID of this message.
"""

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = """
The string `"HandshakeResponse"`.
"""

[fields.selected_protocol_version]
field_name = "selected_protocol_version"
field_type = "string"
optional = false
description = """
The protocol version the CEM selected for this session. This version should be one that was included in the `supported_protocol_versions` field of the exchanged `Handshake`s.
"""
