type_name = "HandshakeResponse"
sent_by = []
description = """
TODO
"""
see_also = []

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = """
ID of this message
"""

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = """
TODO
"""

[fields.selected_protocol_version]
field_name = "selected_protocol_version"
field_type = "string"
optional = false
description = """
The protocol version the CEM selected for this session
"""
