type_name = "NumberRange"
description = '''
TODO
'''

[fields.end_of_range]
field_name = "end_of_range"
field_type = "float"
optional = false
description = '''
Number that defines the end of the range
'''

[fields.start_of_range]
field_name = "start_of_range"
field_type = "float"
optional = false
description = '''
Number that defines the start of the range
'''
