type_name = "OMBC.Status"
sent_by = []
description = """

"""
see_also = []

[fields.active_operation_mode_id]
field_name = "active_operation_mode_id"
field_type = "ID"
optional = false
description = """
ID of the active `OMBC.OperationMode`.
"""

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = """
ID of this message
"""

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = """

"""

[fields.operation_mode_factor]
field_name = "operation_mode_factor"
field_type = "float"
optional = false
description = """
The number indicates the factor with which the `OMBC.OperationMode` should be configured. The factor should be greater than or equal than 0 and less or equal to 1.
"""

[fields.previous_operation_mode_id]
field_name = "previous_operation_mode_id"
field_type = "ID"
optional = true
description = """
ID of the `OMBC.OperationMode` that was previously active. This value shall always be provided, unless the active `OMBC.OperationMode` is the first `OMBC.OperationMode` the Resource Manager is aware of.
"""

[fields.transition_timestamp]
field_name = "transition_timestamp"
field_type = "string"
optional = true
description = """
Time at which the transition from the previous `OMBC.OperationMode` to the active `OMBC.OperationMode` was initiated. This value shall always be provided, unless the active `OMBC.OperationMode` is the first `OMBC.OperationMode` the Resource Manager is aware of.
"""
