type_name = "OMBC.SystemDescription"
sent_by = []
description = '''
TODO
'''

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = '''
ID of this message
'''

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = '''
TODO
'''

[fields.operation_modes]
field_name = "operation_modes"
field_type = "OMBC.OperationMode[]"
optional = false
description = '''
`OMBC.OperationModes` available for the CEM in order to coordinate the device behaviour.
'''

[fields.timers]
field_name = "timers"
field_type = "Timer[]"
optional = false
description = '''
Timers that control when certain transitions can be made.
'''

[fields.transitions]
field_name = "transitions"
field_type = "Transition[]"
optional = false
description = '''
Possible transitions to switch from one `OMBC.OperationMode` to another.
'''

[fields.valid_from]
field_name = "valid_from"
field_type = "string"
optional = false
description = '''
Moment this `OMBC.SystemDescription` starts to be valid. If the system description is immediately valid, the DateTimeStamp should be now or in the past.
'''
