type_name = "PEBC.PowerConstraints"
sent_by = []
description = '''
TODO
'''

[fields.allowed_limit_ranges]
field_name = "allowed_limit_ranges"
field_type = "PEBC.AllowedLimitRange[]"
optional = false
description = '''
The actual constraints. There shall be at least one `PEBC.AllowedLimitRange` for the UPPER_LIMIT and at least one AllowedLimitRange for the LOWER_LIMIT. It is allowed to have multiple `PEBC.AllowedLimitRange` objects with identical CommodityQuantities and LimitTypes.
'''

[fields.consequence_type]
field_name = "consequence_type"
field_type = "PEBC.PowerEnvelopeConsequenceType"
optional = false
description = '''
Type of consequence of limiting power
'''

[fields.id]
field_name = "id"
field_type = "ID"
optional = false
description = '''
Identifier of this `PEBC.PowerConstraints`. Must be unique in the scope of the Resource Manager, for at least the duration of the session between Resource Manager and CEM.
'''

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = '''
ID of this message
'''

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = '''
TODO
'''

[fields.valid_from]
field_name = "valid_from"
field_type = "string"
optional = false
description = '''
Moment this `PEBC.PowerConstraints` start to be valid
'''

[fields.valid_until]
field_name = "valid_until"
field_type = "string"
optional = true
description = '''
Moment until this `PEBC.PowerConstraints` is valid. If valid_until is not present, there is no determined end time of this `PEBC.PowerConstraints`.
'''
