type_name = "PEBC.EnergyConstraint"
sent_by = []
description = """

"""
see_also = []

[fields.commodity_quantity]
field_name = "commodity_quantity"
field_type = "CommodityQuantity"
optional = false
description = """
Type of power quantity which applies to upper_average_power and lower_average_power
"""

[fields.id]
field_name = "id"
field_type = "ID"
optional = false
description = """
Identifier of this `PEBC.EnergyConstraints`. Must be unique in the scope of the Resource Manager, for at least the duration of the session between Resource Manager and CEM.
"""

[fields.lower_average_power]
field_name = "lower_average_power"
field_type = "float"
optional = false
description = """
Lower average power within the time period given by valid_from and valid_until. If the duration is multiplied with this power value, then the associated lower energy content can be derived. This is the lowest amount of energy the resource will consume during that period of time. The Power Envelope created by the CEM must allow at least this much energy production (in case the number is negative). Must be greater than or equal to lower_average_power, and can be negative in case of energy production.
"""

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = """
ID of this message
"""

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = """

"""

[fields.upper_average_power]
field_name = "upper_average_power"
field_type = "float"
optional = false
description = """
Upper average power within the time period given by valid_from and valid_until. If the duration is multiplied with this power value, then the associated upper energy content can be derived. This is the highest amount of energy the resource will consume during that period of time. The Power Envelope created by the CEM must allow at least this much energy consumption (in case the number is positive). Must be greater than or equal to lower_average_power, and can be negative in case of energy production.
"""

[fields.valid_from]
field_name = "valid_from"
field_type = "string"
optional = false
description = """
Moment this `PEBC.EnergyConstraints` information starts to be valid
"""

[fields.valid_until]
field_name = "valid_until"
field_type = "string"
optional = false
description = """
Moment until this `PEBC.EnergyConstraints` information is valid.
"""
