type_name = "PEBC.AllowedLimitRange"
description = '''
TODO
'''

[fields.abnormal_condition_only]
field_name = "abnormal_condition_only"
field_type = "boolean"
optional = false
description = '''
Indicates if this `PEBC.AllowedLimitRange` may only be used during an abnormal condition
'''

[fields.commodity_quantity]
field_name = "commodity_quantity"
field_type = "CommodityQuantity"
optional = false
description = '''
Type of power quantity this `PEBC.AllowedLimitRange` applies to
'''

[fields.limit_type]
field_name = "limit_type"
field_type = "PEBC.PowerEnvelopeLimitType"
optional = false
description = '''
Indicates if this ranges applies to the upper limit or the lower limit
'''

[fields.range_boundary]
field_name = "range_boundary"
field_type = "NumberRange"
optional = false
description = '''
Boundaries of the power range of this `PEBC.AllowedLimitRange`. The CEM is allowed to choose values within this range for the power envelope for the limit as described in limit_type. The start of the range shall be smaller or equal than the end of the range. 
'''
