type_name = "PEBC.PowerEnvelopeConsequenceType"
description = """
TODO
"""
see_also = []

[variants.VANISH]
variant_name = "VANISH"
description = """
Indicating that the limited load or generated will be lost and not reappear in the future (see Clause 7.6.2)
"""

[variants.DEFER]
variant_name = "DEFER"
description = """
Indicating that the limited load or generation will be postponed to a later moment (see Clause 7.6.2)
"""
