type_name = "PEBC.Instruction"
sent_by = ["CEM"]
description = '''
TODO
'''

[fields.abnormal_condition]
field_name = "abnormal_condition"
field_type = "boolean"
optional = false
description = '''
Indicates if this is an instruction during an abnormal condition.
'''

[fields.execution_time]
field_name = "execution_time"
field_type = "string"
optional = false
description = '''
Indicates the moment the execution of the instruction shall start. When the specified execution time is in the past, execution must start as soon as possible.
'''

[fields.id]
field_name = "id"
field_type = "ID"
optional = false
description = '''
Identifier of this `PEBC.Instruction`. Must be unique in the scope of the Resource Manager, for at least the duration of the session between Resource Manager and CEM.
'''

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = '''
ID of this message
'''

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = '''
TODO
'''

[fields.power_constraints_id]
field_name = "power_constraints_id"
field_type = "ID"
optional = false
description = '''
Identifier of the `PEBC.PowerConstraints` this `PEBC.Instruction` was based on.
'''

[fields.power_envelopes]
field_name = "power_envelopes"
field_type = "PEBC.PowerEnvelope[]"
optional = false
description = '''
The `PEBC.PowerEnvelope`(s) that should be followed by the Resource Manager. There shall be at least one `PEBC.PowerEnvelope`, but at most one `PEBC.PowerEnvelope` for each CommodityQuantity.
'''
