type_name = "PEBC.PowerEnvelope"
description = """

"""
see_also = []

[fields.commodity_quantity]
field_name = "commodity_quantity"
field_type = "CommodityQuantity"
optional = false
description = """
Type of power quantity this `PEBC.PowerEnvelope` applies to
"""

[fields.id]
field_name = "id"
field_type = "ID"
optional = false
description = """
Identifier of this `PEBC.PowerEnvelope`. Must be unique in the scope of the Resource Manager, for at least the duration of the session between Resource Manager and CEM.
"""

[fields.power_envelope_elements]
field_name = "power_envelope_elements"
field_type = "PEBC.PowerEnvelopeElement[]"
optional = false
description = """
The elements of this `PEBC.PowerEnvelope`. Shall contain at least one element. Elements must be placed in chronological order.
"""
