type_name = "PowerForecast"
sent_by = ["RM"]
description = """
Forecast of the power values for a future period of time.
"""
see_also = []

[fields.elements]
field_name = "elements"
field_type = "PowerForecastElement[]"
optional = false
description = """
The elements describing the forecast. This must contain at least one element, and elements must be placed in chronological order.
"""

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = """
ID of this message.
"""

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = """
The string `"PowerForecast"`.
"""

[fields.start_time]
field_name = "start_time"
field_type = "string"
optional = false
description = """
Start time of time period that is covered by the profile.
"""
