type_name = "PowerMeasurement"
sent_by = []
description = """
TODO
"""
see_also = []

[fields.measurement_timestamp]
field_name = "measurement_timestamp"
field_type = "string"
optional = false
description = """
Timestamp when PowerValues were measured.
"""

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = """
ID of this message
"""

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = """
TODO
"""

[fields.values]
field_name = "values"
field_type = "PowerValue[]"
optional = false
description = """
Array of measured PowerValues. Must contain at least one item and at most one item per ‘commodity_quantity’ (defined inside the PowerValue).
"""
