type_name = "PowerMeasurement"
sent_by = ["RM"]
description = """
Message containing one or more power measurements.

This message informs the CEM about power values measured by the RM's device. A well-behaved RM should send `PowerMeasurement`s periodically if possible.
"""
see_also = []

[fields.measurement_timestamp]
field_name = "measurement_timestamp"
field_type = "string"
optional = false
description = """
Timestamp when the power values were measured.
"""

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = """
ID of this message.
"""

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = """
The string `"PowerMeasurement"`.
"""

[fields.values]
field_name = "values"
field_type = "PowerValue[]"
optional = false
description = """
The measured `PowerValue`s. Must contain at least one item, and at most one item per `CommodityQuantity`.
"""
