type_name = "PowerForecastElement"
sent_by = []
description = """
Specifies power forecast values valid for a duration.
"""
see_also = []

[fields.duration]
field_name = "duration"
field_type = "Duration"
optional = false
description = """
Duration of this `PowerForecastElement`.
"""

[fields.power_values]
field_name = "power_values"
field_type = "PowerForecastValue[]"
optional = false
description = """
The values of power that are expected for the given period of time. There must be at least one `PowerForecastValue`, and at most one `PowerForecastValue` per `CommodityQuantity`.
"""
