type_name = "PPBC.PowerSequenceElement"
description = """

"""
see_also = []

[fields.duration]
field_name = "duration"
field_type = "Duration"
optional = false
description = """
Duration of the `PPBC.PowerSequenceElement`.
"""

[fields.power_values]
field_name = "power_values"
field_type = "PowerForecastValue[]"
optional = false
description = """
The value of power and deviations for the given duration. The array should contain at least one PowerForecastValue and at most one PowerForecastValue per CommodityQuantity.
"""
