type_name = "PPBC.EndInterruptionInstruction"
sent_by = []
description = '''
TODO
'''

[fields.abnormal_condition]
field_name = "abnormal_condition"
field_type = "boolean"
optional = false
description = '''
Indicates if this is an instruction during an abnormal condition
'''

[fields.execution_time]
field_name = "execution_time"
field_type = "string"
optional = false
description = '''
Indicates the moment `PPBC.PowerSequence` interruption shall end. When the specified execution time is in the past, execution must start as soon as possible.
'''

[fields.id]
field_name = "id"
field_type = "ID"
optional = false
description = '''
ID of the Instruction. Must be unique in the scope of the Resource Manager, for at least the duration of the session between Resource Manager and CEM.
'''

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = '''
ID of this message
'''

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = '''
TODO
'''

[fields.power_profile_id]
field_name = "power_profile_id"
field_type = "ID"
optional = false
description = '''
ID of the `PPBC.PowerProfileDefinition` of which the `PPBC.PowerSequence` interruption is being ended by the CEM.
'''

[fields.power_sequence_id]
field_name = "power_sequence_id"
field_type = "ID"
optional = false
description = '''
ID of the `PPBC.PowerSequence` for which the CEM wants to end the interruption.
'''

[fields.sequence_container_id]
field_name = "sequence_container_id"
field_type = "ID"
optional = false
description = '''
ID of the `PPBC.PowerSequnceContainer` of which the `PPBC.PowerSequence` interruption is being ended by the CEM.
'''
