type_name = "PPBC.PowerSequenceStatus"
description = '''
TODO
'''

[variants.NOT_SCHEDULED]
variant_name = "NOT_SCHEDULED"
description = '''
No `PPBC.PowerSequence` within the `PPBC.PowerSequenceContainer` is scheduled
'''

[variants.SCHEDULED]
variant_name = "SCHEDULED"
description = '''
The selected `PPBC.PowerSequence` is scheduled to be executed in the future
'''

[variants.EXECUTING]
variant_name = "EXECUTING"
description = '''
The selected `PPBC.PowerSequence` is currently being executed
'''

[variants.INTERRUPTED]
variant_name = "INTERRUPTED"
description = '''
The selected `PPBC.PowerSequence` is being executed, but is currently interrupted and will continue afterwards
'''

[variants.FINISHED]
variant_name = "FINISHED"
description = '''
The selected `PPBC.PowerSequence` was executed and finished successfully
'''

[variants.ABORTED]
variant_name = "ABORTED"
description = '''
The selected `PPBC.PowerSequence` was aborted by the device and will not continue
'''
