type_name = "ReceptionStatus"
sent_by = ["CEM", "RM"]
description = '''
TODO
'''

[fields.diagnostic_label]
field_name = "diagnostic_label"
field_type = "string"
optional = true
description = '''
Diagnostic label that can be used to provide additional information for debugging. However, not for HMI purposes.
'''

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = '''
TODO
'''

[fields.status]
field_name = "status"
field_type = "ReceptionStatusValues"
optional = false
description = '''
Enumeration of status values
'''

[fields.subject_message_id]
field_name = "subject_message_id"
field_type = "ID"
optional = false
description = '''
The message this ReceptionStatus refers to
'''
