type_name = "ResourceManagerDetails"
sent_by = ["RM"]
description = """
Describes various properties of an RM.

The RM sends this message after the handshaking process has taken place to let the CEM know about its various property. Importantly, `available_control_types` lets the CEM know what control types the RM supports. The CEM will then usually respond with a `SelectControlType` message to select one of the supported control types.
"""
see_also = []

[fields.available_control_types]
field_name = "available_control_types"
field_type = "ControlType[]"
optional = false
description = """
The control types supported by this Resource Manager.
"""

[fields.currency]
field_name = "currency"
field_type = "Currency"
optional = true
description = """
Currency to be used for all information regarding costs. Mandatory if cost information is published.
"""

[fields.firmware_version]
field_name = "firmware_version"
field_type = "string"
optional = true
description = """
Version identifier of the firmware used in the device (provided by the manufacturer)
"""

[fields.instruction_processing_delay]
field_name = "instruction_processing_delay"
field_type = "Duration"
optional = false
description = """
The average time the combination of Resource Manager and HBES/BACS/SASS or (Smart) device needs to process and execute an instruction
"""

[fields.manufacturer]
field_name = "manufacturer"
field_type = "string"
optional = true
description = """
The name of this resource's manufacturer.
"""

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = """
ID of this message.
"""

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = """
The string `"ResourceManagerDetails"`.
"""

[fields.model]
field_name = "model"
field_type = "string"
optional = true
description = """
The name of the model of the device (provided by the manufacturer).
"""

[fields.name]
field_name = "name"
field_type = "string"
optional = true
description = """
A human readable name given by the user of the resource.
"""

[fields.provides_forecast]
field_name = "provides_forecast"
field_type = "boolean"
optional = false
description = """
Indicates whether the ResourceManager is able to provide `PowerForecast`s.
"""

[fields.provides_power_measurement_types]
field_name = "provides_power_measurement_types"
field_type = "CommodityQuantity[]"
optional = false
description = """
Indicates for which CommodityQuantities this Resource Manager can provide measurements. 
"""

[fields.resource_id]
field_name = "resource_id"
field_type = "ID"
optional = false
description = """
Unique identifier of the Resource Manager.
"""

[fields.roles]
field_name = "roles"
field_type = "Role[]"
optional = false
description = """
Describes which commodities the resource can consume, produce and/or store.
"""

[fields.serial_number]
field_name = "serial_number"
field_type = "string"
optional = true
description = """
The serial number of the device (provided by the manufacturer).
"""
