type_name = "ResourceManagerDetails"
sent_by = []
description = '''
TODO
'''

[fields.available_control_types]
field_name = "available_control_types"
field_type = "ControlType[]"
optional = false
description = '''
The control types supported by this Resource Manager.
'''

[fields.currency]
field_name = "currency"
field_type = "Currency"
optional = true
description = '''
Currency to be used for all information regarding costs. Mandatory if cost information is published.
'''

[fields.firmware_version]
field_name = "firmware_version"
field_type = "string"
optional = true
description = '''
Version identifier of the firmware used in the device (provided by the manufacturer)
'''

[fields.instruction_processing_delay]
field_name = "instruction_processing_delay"
field_type = "Duration"
optional = false
description = '''
The average time the combination of Resource Manager and HBES/BACS/SASS or (Smart) device needs to process and execute an instruction
'''

[fields.manufacturer]
field_name = "manufacturer"
field_type = "string"
optional = true
description = '''
Name of Manufacturer
'''

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = '''
ID of this message
'''

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = '''
TODO
'''

[fields.model]
field_name = "model"
field_type = "string"
optional = true
description = '''
Name of the model of the device (provided by the manufacturer)
'''

[fields.name]
field_name = "name"
field_type = "string"
optional = true
description = '''
Human readable name given by user
'''

[fields.provides_forecast]
field_name = "provides_forecast"
field_type = "boolean"
optional = false
description = '''
Indicates whether the ResourceManager is able to provide PowerForecasts
'''

[fields.provides_power_measurement_types]
field_name = "provides_power_measurement_types"
field_type = "CommodityQuantity[]"
optional = false
description = '''
Array of all CommodityQuantities that this Resource Manager can provide measurements for. 
'''

[fields.resource_id]
field_name = "resource_id"
field_type = "ID"
optional = false
description = '''
Identifier of the Resource Manager. Must be unique within the scope of the CEM.
'''

[fields.roles]
field_name = "roles"
field_type = "Role[]"
optional = false
description = '''
Each Resource Manager provides one or more energy Roles
'''

[fields.serial_number]
field_name = "serial_number"
field_type = "string"
optional = true
description = '''
Serial number of the device (provided by the manufacturer)
'''
