type_name = "RevokableObjects"
description = """

"""
see_also = []

[variants."PEBC.PowerConstraints"]
variant_name = "PEBC.PowerConstraints"
description = """
Object type `PEBC.PowerConstraints`
"""

[variants."PEBC.EnergyConstraint"]
variant_name = "PEBC.EnergyConstraint"
description = """
Object type `PEBC.EnergyConstraint`
"""

[variants."PEBC.Instruction"]
variant_name = "PEBC.Instruction"
description = """
Object type `PEBC.Instruction`
"""

[variants."PPBC.PowerProfileDefinition"]
variant_name = "PPBC.PowerProfileDefinition"
description = """
Object type `PPBC.PowerProfileDefinition`
"""

[variants."PPBC.ScheduleInstruction"]
variant_name = "PPBC.ScheduleInstruction"
description = """
Object type `PPBC.ScheduleInstruction`
"""

[variants."PPBC.StartInterruptionInstruction"]
variant_name = "PPBC.StartInterruptionInstruction"
description = """
Object type `PPBC.StartInterruptionInstruction`
"""

[variants."PPBC.EndInterruptionInstruction"]
variant_name = "PPBC.EndInterruptionInstruction"
description = """
Object type `PPBC.EndInterruptionInstruction`
"""

[variants."OMBC.SystemDescription"]
variant_name = "OMBC.SystemDescription"
description = """
Object type `OMBC.SystemDescription`
"""

[variants."OMBC.Instruction"]
variant_name = "OMBC.Instruction"
description = """
Object type `OMBC.Instruction`
"""

[variants."FRBC.SystemDescription"]
variant_name = "FRBC.SystemDescription"
description = """
Object type `FRBC.SystemDescription`
"""

[variants."FRBC.LeakageBehaviour"]
variant_name = "FRBC.LeakageBehaviour"
description = """
Object type `FRBC.LeakageBehaviour`
"""

[variants."FRBC.UsageForecast"]
variant_name = "FRBC.UsageForecast"
description = """
Object type `FRBC.UsageForecast`
"""

[variants."FRBC.FillLevelTargetProfile"]
variant_name = "FRBC.FillLevelTargetProfile"
description = """
Object type `FRBC.FillLevelTargetProfile`
"""

[variants."FRBC.Instruction"]
variant_name = "FRBC.Instruction"
description = """
Object type `FRBC.Instruction`
"""

[variants."DDBC.SystemDescription"]
variant_name = "DDBC.SystemDescription"
description = """
Object type `DDBC.SystemDescription`
"""

[variants."DDBC.AverageDemandRateForecast"]
variant_name = "DDBC.AverageDemandRateForecast"
description = """
Object type `DDBC.AverageDemandRateForecast`
"""

[variants."DDBC.Instruction"]
variant_name = "DDBC.Instruction"
description = """
Object type `DDBC.Instruction`
"""
