type_name = "Role"
description = """
TODO
"""
see_also = []

[fields.commodity]
field_name = "commodity"
field_type = "Commodity"
optional = false
description = """
Commodity the role refers to.
"""

[fields.role]
field_name = "role"
field_type = "RoleType"
optional = false
description = """
Role type of the Resource Manager for the given commodity
"""
