type_name = "Role"
description = """
Describes that a resource can consume, produce or store a commodity.
"""
see_also = []

[fields.commodity]
field_name = "commodity"
field_type = "Commodity"
optional = false
description = """
The commodity being referred to.
"""

[fields.role]
field_name = "role"
field_type = "RoleType"
optional = false
description = """
Indicates whether the resourse can consume, produce or store the specified commodity.
"""
