type_name = "SelectControlType"
sent_by = ["CEM"]
description = """
Activates a Control Type for this session.

This message is sent by the CEM to activate a Control Type for this session. The activated control type must be supported by the Resource Manager (as indicated in `ResourceManagerDetails` received by the CEM).
"""
see_also = [{ name = "Guide to S2 control types", link = "https://docs.s2standard.org/docs/concepts/control-types/" }]

[fields.control_type]
field_name = "control_type"
field_type = "ControlType"
optional = false
description = """
The Control Type to activate.
"""

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = """
ID of this message.
"""

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = """
The string `"SelectControlType"`.
"""
