type_name = "SelectControlType"
sent_by = ["CEM"]
description = '''
TODO
'''

[fields.control_type]
field_name = "control_type"
field_type = "ControlType"
optional = false
description = '''
The ControlType to activate. Must be one of the available ControlTypes as defined in the ResourceManagerDetails
'''

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = '''
ID of this message
'''

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = '''
TODO
'''
