type_name = "SessionRequestType"
description = '''

'''

[variants.RECONNECT]
variant_name = "RECONNECT"
description = '''
Please reconnect the WebSocket session. Once reconnected, it starts from scratch with a handshake.
'''

[variants.TERMINATE]
variant_name = "TERMINATE"
description = '''
Disconnect the session (client can try to reconnecting with exponential backoff)
'''
