type_name = "SessionRequest"
sent_by = []
description = """

"""
see_also = []

[fields.diagnostic_label]
field_name = "diagnostic_label"
field_type = "string"
optional = true
description = """
Optional field for a human readible descirption for debugging purposes
"""

[fields.message_id]
field_name = "message_id"
field_type = "ID"
optional = false
description = """
ID of this message
"""

[fields.message_type]
field_name = "message_type"
field_type = "string"
optional = false
description = """

"""

[fields.request]
field_name = "request"
field_type = "SessionRequestType"
optional = false
description = """
The type of request
"""
