[package]
name = "s2-documentation-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = { version = "2.8.0", features = ["serde"] }
regex = "1.11.1"
schemars = "0.8.22"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.8.20"
